# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

udunits_init <- function(path) {
    invisible(.Call('_units_udunits_init', PACKAGE = 'units', path))
}

udunits_exit <- function() {
    invisible(.Call('_units_udunits_exit', PACKAGE = 'units'))
}

R_ut_is_parseable <- function(a) {
    .Call('_units_R_ut_is_parseable', PACKAGE = 'units', a)
}

R_ut_are_convertible <- function(a, b) {
    .Call('_units_R_ut_are_convertible', PACKAGE = 'units', a, b)
}

R_ut_convert_doubles <- function(from, to, val) {
    .Call('_units_R_ut_convert_doubles', PACKAGE = 'units', from, to, val)
}

R_ut_new_dimensionless_unit <- function(name) {
    invisible(.Call('_units_R_ut_new_dimensionless_unit', PACKAGE = 'units', name))
}

R_ut_scale <- function(nw, old, d) {
    invisible(.Call('_units_R_ut_scale', PACKAGE = 'units', nw, old, d))
}

R_ut_offset <- function(nw, old, d) {
    invisible(.Call('_units_R_ut_offset', PACKAGE = 'units', nw, old, d))
}

R_ut_set_encoding <- function(enc_str) {
    invisible(.Call('_units_R_ut_set_encoding', PACKAGE = 'units', enc_str))
}

R_ut_get_symbol <- function(ustr) {
    .Call('_units_R_ut_get_symbol', PACKAGE = 'units', ustr)
}

R_ut_get_name <- function(ustr) {
    .Call('_units_R_ut_get_name', PACKAGE = 'units', ustr)
}

