# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

udunits_init <- function(path, warn_on_failure = FALSE) {
    .Call('_units_udunits_init', PACKAGE = 'units', path, warn_on_failure)
}

R_ut_parse <- function(name) {
    .Call('_units_R_ut_parse', PACKAGE = 'units', name)
}

R_ut_format <- function(p, names = FALSE, definition = FALSE) {
    .Call('_units_R_ut_format', PACKAGE = 'units', p, names, definition)
}

